### ISSUE TITLE
_curses.error: init_pair() returned ERR

### ISSUE THREAD

**Issue by uid89626** [xoreaxeaxeax/sandsifter#14]
Python 2.7.6

Traceback (most recent call last):
                                    File "./sifter.py", line 842, in <module>
                                                                                 main()
         File "./sifter.py", line 833, in main
                                                  gui = Gui(ts, injector, tests, args.tick)
             File "./sifter.py", line 376, in __init__
                                                          self.init_colors()
                                                                              File "./sifter.py", line 423, in init_colors
                                              self.COLOR_BLACK
                                                              _curses.error: init_pair() returned ERR

**Comment by drpixie** [comment]
Workaround - try **export TERM='xterm-256color'** before starting sifter. I guess your default terminal isn't 256 colour (same as my Linux Mint).

**Comment by f4grx** [comment]
same issue here, just fake the TERM variable and it works.

**Comment by Tsutsukakushi** [comment]
What is the point of using such colors and not having any fallback to the default colors available on allmost all terminals? Sure the program will run on a terminal without 256 color palette but it won't be drawn correctly.

**Comment by cpatulea** [comment]
Set TERM=xterm-256color, still error:

```
Traceback (most recent call last):
                                    File "./summarize.py", line 751, in <module>
                                                                                    textbox.draw()
                                                                                                    File "/home/catalinp/src/phi/sandsifter/gui/gui.py", line 68, in draw
                                       self.gui.box(self.window, self.x, self.y, self.w, self.h, self.color)
                                                                                                              File "/home/catalinp/src/phi/sandsifter/gui/gui.py", line 175, in box
                                                 window.addch(y + h - 1, x + i, curses.ACS_HLINE, color)
                                                                                                        _curses.error: addch() returned ERR
```

EDIT: resized my terminal to make it bigger, now works
