### ISSUE TITLE
Injector hang

### ISSUE THREAD

**Issue by m3gat0nn4ge** [xoreaxeaxeax/sandsifter#23]
Hi,

Injector seems to be hanging on Fedora 23 after ~1B instruction tests, selinux is in permissive mode, cpu is Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz.

I've tried twice, going to attach using strace this time and see if anything is happening but in the meantime, any ideas?

thanks

![injector hang](https://user-images.githubusercontent.com/13809912/28758119-e75d447e-75d5-11e7-856a-9671fd328d7b.png)

**Comment by m3gat0nn4ge** [comment]
Ok .. so it seems to be stopping at the exact same point so I guess it has completed checking all the possible combinations. Attaching with strace gave me a stack of the following:

`17738 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
17738 rt_sigreturn({mask=[]})           = 0
17738 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
17738 rt_sigreturn({mask=[]})           = 0
17738 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
17738 rt_sigreturn({mask=[]})           = 0
17738 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
17738 rt_sigreturn({mask=[]})           = 0
17738 --- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
17738 rt_sigreturn({mask=[]})           = 0
`

**Comment by m3gat0nn4ge** [comment]
This time I also left the terminal active while killing the injector process and saw a stack of output. The summarize command doesn't work however:

`Traceback (most recent call last):
                                    File "./summarize.py", line 751, in <module>
                                                                                   textbox.draw()
                   File "/home/me/Documents/sandsifter/gui/gui.py", line 68, in draw
             self.gui.box(self.window, self.x, self.y, self.w, self.h, self.color)
    File "/home/me/Documents/sandsifter/gui/gui.py", line 175, in box
                                                                              window.addch(y + h - 1, x + i, curses.ACS_HLINE, color)
                                                     _curses.error: addch() returned ERR
`

**Comment by rupran** [comment]
For the last error, try using a slightly bigger terminal window.

Anything smaller than **97x40** will probably always lead to the same error, as the `draw_infobox` function currently works with fixed values: 
- it draws one box from offset (37,3) with width 60 (at https://github.com/xoreaxeaxeax/sandsifter/blob/master/summarize.py#L605)
- it writes the help strings to y-offsets 33-39 (at https://github.com/xoreaxeaxeax/sandsifter/blob/master/summarize.py#L755 and the following lines)

**Comment by m3gat0nn4ge** [comment]
Thanks @rupran .. summarize is working, now to analyze the results...
