### ISSUE TITLE
Sandsifter stops running. Capstone installed via pip.

### ISSUE THREAD

**Issue by greg5678** [xoreaxeaxeax/sandsifter#39]
I downloaded a copy of sandsifter from github. I then compiled with sudo make -j8. 
`sudo make -j8
cc  -c injector.c -o injector.o -Wall
injector.c:321:2: warning: excess elements in array initializer [enabled by default]
  .start={.bytes={0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}, .len=0},
  ^
injector.c:321:2: warning: (near initialization for 'total_range.start.bytes') [enabled by default]
injector.c:322:2: warning: excess elements in array initializer [enabled by default]
  .end={.bytes={0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff}, .len=0},
  ^
injector.c:322:2: warning: (near initialization for 'total_range.end.bytes') [enabled by default]
cc  injector.o -O3 -Wall -l:libcapstone.a -o injector -pthread`

I ran sandsifter and it gave me this error.
`sudo ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
Traceback (most recent call last):
  File "./sifter.py", line 842, in <module>
    main()
  File "./sifter.py", line 815, in main
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
I ran it again but now it gave me a new problem. Sandsifter opens but it doesn't continue to run.
`sudo ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
#
# ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
# ./injector -P1 -t -t -R -0 -s 2540215650
#
# insn tested: 0
# artf found:  0
# runtime:     00:00:00.05
# seed:        2540215650
# arch:        64
# date:        2017-09-02 21:39:54
#
# cpu:
# processor     : 0
# vendor_id     : GenuineIntel
# cpu family    : 6
# model         : 45
# model name    : Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
# stepping      : 7
# microcode     : 4294967295
#                               v  l  s  c`

**Comment by qwerty123443** [comment]
I have the same issue: 
```
#
# ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
# ./injector -P1 -t -t -R  -s 3150103237
#
# insn tested: 352
# artf found:  83
# runtime:     00:00:00.17
# seed:        3150103237
# arch:        64
# date:        2017-09-09 11:16:36
#
# cpu:
# processor     : 0
# vendor_id     : GenuineIntel
# cpu family    : 6
# model         : 61
# model name    : Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
# stepping      : 4
# microcode     : 0xffffffff
#
```

**Comment by qwerty123443** [comment]
@greg5678 use \`\`\` (triple backtick) for your code blocks and not \` (single backtick)
