### ISSUE TITLE
_curses.error: init_pair()

### ISSUE THREAD

**Issue by JiangwNd** [xoreaxeaxeax/sandsifter#50]
Traceback (most recent call last):
                                    File "./sifter.py", line 842, in <module>
                                                                                 main()
         File "./sifter.py", line 833, in main
                                                  gui = Gui(ts, injector, tests, args.tick)
             File "./sifter.py", line 376, in __init__
                                                          self.init_colors()
                                                                              File "./sifter.py", line 423, in init_colors
                                              self.COLOR_BLACK
                                                              _curses.error: init_pair() returned ERR

**Comment by mazzoo** [comment]
you can use one of those fancy g* or k* terminal programs as workaround.
