### ISSUE TITLE
File "./sifter.py", line 817, in main arch = re.search(r".*(..)-bit.*", injector_bitness).group(1)

### ISSUE THREAD

**Issue by blastwave** [xoreaxeaxeax/sandsifter#71]
Made the attempt to use this on a Debian sid based system which is twenty year old hardware. The processors are real Intel Pentium II ( Deschutes ) modules and there are two of them.

However : 

titan# ./sifter.py --unk --dis --len --sync --tick -- -P1 -t
Traceback (most recent call last):
  File "./sifter.py", line 842, in <module>
    main()
  File "./sifter.py", line 817, in main
    arch = re.search(r".*(..)-bit.*", injector_bitness).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
titan# 

titan#  git remote show origin
* remote origin
  Fetch URL: https://github.com/xoreaxeaxeax/sandsifter
  Push  URL: https://github.com/xoreaxeaxeax/sandsifter
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
titan# 

Not sure what to do with that other than just let you know. 

-- 
Dennis Clarke
RISC-V/SPARC/PPC/ARM/CISC
UNIX and Linux spoken
GreyBeard and suspenders included

**Comment by blastwave** [comment]
I am going to guess that 32-bit systems are out of the question.

**Comment by CompaqDisc** [comment]
Can reproduce on my Arch Linux setup, running on a Ryzen 5 2600.

```
compaqdisc@keystone:~/sandsifter$ sudo python2.7 sifter.py --unk --dis --len --sync --tick -- -P1 -t
Traceback (most recent call last):
  File "sifter.py", line 842, in <module>
    main()
  File "sifter.py", line 817, in main
    arch = re.search(r".*(..)-bit.*", injector_bitness).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
compaqdisc@keystone:~/sandsifter$ uname -a
Linux keystone 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
```

**Comment by CompaqDisc** [comment]
Commenting out the line and replacing with `arch = 64-bit` worked for me, but I'd hazard a guess that any string may be fine there.

**Comment by mkdahan** [comment]
the same issue for me,
Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz processor
If changing to arch = '64-bit'
get this summary:
 insn tested: 0 
 artf found:  0 
 runtime:     00:00:00.21 
 seed:        2552905624 
 arch:        64-bit 
 date:        2020-12-01 12:35:24 

 cpu: 
 processor     : 0 
 vendor_id     : GenuineIntel 
 cpu family    : 6 
 model         : 23 
 model name    : Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz 
 stepping      : 10 
 microcode     : 0xffffffff

**Comment by spencerpogo** [comment]
Happened to me, you need to run `make` first. (`make CFLAGS=-no-pie` specifically)
